#!/usr/bin/env bash

if [[ ! -f points.csv ]]; then
  printf 'wtf are you doing?\n' >&2
  exit 42
fi

{
  printf '# Points\n'
  printf '\n'
  printf 'The amount of points earned by each bastard\n'
  printf '\n'

  while IFS= read -r row; do
    printf '  * `%s`: %d\n' "${row%,*}" "${row##*,}"
  done < points.csv

  printf '\n'
} > README.md
